### ISSUE TITLE
export model ModuleNotFoundError: No module named 'bioimageio.core.build_spec

### ISSUE THREAD

**Issue by kwiechen** [instanseg/instanseg#22]
Hi,

I have trained a new model without problems. The export model notebook shows this ModuleNotFoundError but bioimageio.core is installed.

Best regards,

Kai

**Comment by alanocallaghan** [comment]
Which version do you have? The environment spec calls for: 

```
  - bioimageio.core=0.5.11
  - bioimageio.spec=0.4.9
```

**Comment by kwiechen** [comment]
no there was a version possibly incompatible - now I have installed 
       
bioimageio.core==0.5.11
bioimageio.spec==0.4.9

The ModulesNotFoundError is now 

ModuleNotFoundError: No module named 'bioimageio.spec.model.v0_4.raw_nodes'; 'bioimageio.spec.model.v0_4' is not a package

I am using Windows 10

**Comment by kwiechen** [comment]
[autoreload of bioimageio.spec.dataset failed: Traceback (most recent call last):
  File "c:\Users\kai\source\repos\instanseg\.venv\lib\site-packages\IPython\extensions\autoreload.py", line 276, in check
    superreload(m, reload, self.old_objects)
  File "c:\Users\kai\source\repos\instanseg\.venv\lib\site-packages\IPython\extensions\autoreload.py", line 475, in superreload
    module = reload(module)
  File "C:\Users\kai\python-310-11-64\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\Users\kai\source\repos\instanseg\.venv\lib\site-packages\bioimageio\spec\dataset\__init__.py", line 4, in <module>
    from . import converters, raw_nodes, schema, utils
  File "c:\Users\kai\source\repos\instanseg\.venv\lib\site-packages\bioimageio\spec\dataset\converters.py", line 3, in <module>
    from .v0_2.converters import *
ModuleNotFoundError: No module named 'bioimageio.spec.dataset.v0_2.converters'; 'bioimageio.spec.dataset.v0_2' is not a package
]
site.config.json: 6.61kiB [00:00, 6.43MiB/s]                  
c:\Users\kai\source\repos\instanseg\.venv\lib\site-packages\bioimageio\spec\shared\_resolve_source.py:471: UserWarning: Download (6609) does not have expected size (2308).
  warnings.warn(f"Download ({t.n}) does not have expected size ({total_size}).")
collection.json: 235kiB [00:00, 78.4MiB/s]                   
c:\Users\kai\source\repos\instanseg\.venv\lib\site-packages\bioimageio\spec\shared\_resolve_source.py:471: UserWarning: Download (234788) does not have expected size (28539).
  warnings.warn(f"Download ({t.n}) does not have expected size ({total_size}).")
[autoreload of bioimageio.spec.model failed: Traceback (most recent call last):
  File "c:\Users\kai\source\repos\instanseg\.venv\lib\site-packages\IPython\extensions\autoreload.py", line 276, in check
    superreload(m, reload, self.old_objects)
  File "c:\Users\kai\source\repos\instanseg\.venv\lib\site-packages\IPython\extensions\autoreload.py", line 475, in superreload
    module = reload(module)
  File "C:\Users\kai\python-310-11-64\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\Users\kai\source\repos\instanseg\.venv\lib\site-packages\bioimageio\spec\model\__init__.py", line 4, in <module>
    from . import converters, raw_nodes, schema, utils
  File "c:\Users\kai\source\repos\instanseg\.venv\lib\site-packages\bioimageio\spec\model\converters.py", line 3, in <module>
    from .v0_4.converters import *
ModuleNotFoundError: No module named 'bioimageio.spec.model.v0_4.converters'; 'bioimageio.spec.model.v0_4' is not a package
]

**Comment by alanocallaghan** [comment]
Hmm, bit concerned by the two download warnings:
```
UserWarning: Download (6609) does not have expected size (2308).
```
and 

```
UserWarning: Download (234788) does not have expected size (28539).
```

for site.config.json and collections.json, though I'm not sure what they correspond to

**Comment by kwiechen** [comment]
I will try to install in Linux/WSL

**Comment by alanocallaghan** [comment]
To use with QuPath, you will need a directory similar to the downloaded models:

```
brightfield_nuclei
├── brightfield_nuclei_README.md
├── cover.png
├── instanseg_postprocess.ijm
├── instanseg_preprocess.ijm
├── instanseg.pt
├── per_sample_scale_range.ijm
├── rdf.yaml
├── sample_input_0.tif
├── sample_output_0.tif
├── test-input.npy
└── test-output.npy
```

but at the very least you need a valid `rdf.yaml` and `modelname.pt` file in a directory. You can then add this directory to the "downloaded models directory" that you set in the instanseg extension, and they should be picked up (you may need to relaunch QuPath)

**Comment by kwiechen** [comment]
I have added the rdf.yaml from your brightfield_nuclei model to my model and this works (for now with cpu, I will try to solve the cuda problems).
