### ISSUE TITLE
error training with PanNuke #2

### ISSUE THREAD

**Issue by kwiechen** [instanseg/instanseg#24]
Usng the PanNuke dataset with -augmentation_type heavy/brightfield_only 

python train.py -data segmentation_dataset.pth --num_epochs 250 --experiment_str my_first_instanseg --requested_pixel_size 0.43 -e_s pannuke043augmentationbrightfield -source "[PanNuke]" -augmentation_type brightfield_only

results after 1 or 2 epochs

Epoch: 0
 57%|█████████████████████████████████████████████████████████████████████████████▌                                                         | 192/334 [00:39<00:29,  4.88it/s]
Traceback (most recent call last):
  File "/home/kai/instanseg/InstanSeg/scripts/train.py", line 324, in <module>
    model, train_losses, test_losses, f1_list, f1_list_cells = main(model, loss_fn, train_loader, test_loader, num_epochs=hot_epochs, epoch_name='hotstart_epoch')
  File "/home/kai/instanseg/InstanSeg/scripts/train.py", line 92, in main
    train_loss, train_time = train_epoch(model, device, train_loader, loss_fn, optimizer, args = args, writer = writer)
  File "/home/kai/instanseg/InstanSeg/utils/AI_utils.py", line 36, in train_epoch
    for image_batch, labels_batch, _ in tqdm(train_dataloader, disable=args.on_cluster):
  File "/home/kai/micromamba/envs/instanseg/lib/python3.9/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/home/kai/micromamba/envs/instanseg/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/kai/micromamba/envs/instanseg/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/kai/micromamba/envs/instanseg/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/kai/micromamba/envs/instanseg/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/kai/micromamba/envs/instanseg/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/kai/micromamba/envs/instanseg/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kai/micromamba/envs/instanseg/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kai/instanseg/InstanSeg/utils/AI_utils.py", line 205, in __getitem__
    data, label = self.Augmenter(data, label, meta)
  File "/home/kai/instanseg/InstanSeg/utils/augmentations.py", line 821, in __call__
    image, labels = getattr(self, augmentation)(image, labels, amount=amount, metadata=metadata)
  File "/home/kai/instanseg/InstanSeg/utils/augmentations.py", line 173, in extract_eosin_stain
    norm, H, E = normalizer.normalize(I=tensor, stains=True, Io=240)
  File "/home/kai/micromamba/envs/instanseg/lib/python3.9/site-packages/torchstain/torch/normalizers/macenko.py", line 104, in normalize
    HE, C, maxC = self.__compute_matrices(I, Io, alpha, beta)
  File "/home/kai/micromamba/envs/instanseg/lib/python3.9/site-packages/torchstain/torch/normalizers/macenko.py", line 67, in __compute_matrices
    HE = self.__find_HE(ODhat, eigvecs, alpha)
  File "/home/kai/micromamba/envs/instanseg/lib/python3.9/site-packages/torchstain/torch/normalizers/macenko.py", line 38, in __find_HE
    minPhi = percentile(phi, alpha)
  File "/home/kai/micromamba/envs/instanseg/lib/python3.9/site-packages/torchstain/torch/utils/percentile.py", line 24, in percentile
    return t.view(-1).kthvalue(k).values
IndexError: kthvalue(): Expected reduction dim 0 to have non-zero size.

I think the problem are training images from PanNuke containing no tissue with or without ink marks. It may be possible to remove those image data from the training set. But I think it may be better to modify the stain tools.

**Comment by ThibautGoldsborough** [comment]
I'll try and reproduce the error, but in the meanwhile you should stick to augmentation type "minimal" and "heavy". "brightfield_only" is experimental, the original aim was to make fluorescence images look like brightfield images during training.

**Comment by kwiechen** [comment]
I also got this error with augmentation_type heavy when using the PanNuke dataset. I have commented out 

   ("normalize_HE_stains", [0.1, amount*0]), #Probability/Amount, make sure this goes in front of normalize
   ("extract_eosin_stain", [0.1, amount*0]), #Probability/Amount ,make sure this goes in front of normalize

in augmentation_config trying to solve this. Unfortunately there is also issue PanNuke #1. 

However for now I have trained for our pixel size 0.43 microns using the other brightfield datasets using augmentation type heavy and brightfield_only with comparable results

**Comment by kwiechen** [comment]
removing images without tissue or nuclei from PanNuke solves this problem 
`
from skimage.color import rgb2hed



hed = rgb2hed(image)
if np.max(hed[:, :, 0]) > 0.05:
                tifffile.imwrite(out_path / ("image_"+str(i)+".tif"),image)
                tifffile.imwrite(out_path / ("nucleus_masks_"+str(i)+".tif"),fastremap.refit(fastremap.renumber(label)[0]))
                tifffile.imwrite(out_path / ("class_masks_"+str(i)+".tif"),classes)

                relative_path_img = os.path.relpath(str(out_path / ("image_"+str(i)+".tif")),os.environ['INSTANSEG_DATASET_PATH'])
                relative_path_nucleus = os.path.relpath(str(out_path / ("nucleus_masks_"+str(i)+".tif")),os.environ['INSTANSEG_DATASET_PATH'])
                relative_path_class = os.path.relpath(str(out_path / ("class_masks_"+str(i)+".tif")),os.environ['INSTANSEG_DATASET_PATH'])

                item['image']=relative_path_img
                item['nucleus_masks']= relative_path_nucleus
                item['class_masks']= relative_path_class

                item["parent_dataset"]="PanNuke"
                item['licence']="Attribution-NonCommercial-ShareAlike 4.0 International"
                item['image_modality']="Brightfield"
                item['pixel_size']= 0.25   #In microns per pixel
                item['tissue_type']= types[i]
                
                items.append(item)`
