### ISSUE TITLE
Error running inference on example image

### ISSUE THREAD

**Issue by gunjan-sh** [instanseg/instanseg#26]
Hello,
 
I am trying to run the inference.py on the given example images using the given fluorescence_nuclei_and_cells pretrained model.
I ran this command :
`CUDA_VISIBLE_DEVICES=1 python inference.py --model_folder fluorescence_nuclei_and_cells --image_path ../examples --pixel_size 0.5`
 
I got an error without the pixel-size parameter, so I tried with --pixel-size as 0.5 taking a reference from segmentation_minimal.ipynb.

Got following error:

> 
> (instanseg) [gsh@pctrl1 scripts]$ CUDA_VISIBLE_DEVICES=1 python inference.py --model_folder fluorescence_nuclei_and_cells --image_path ../examples --pixel_size 0.5
> /home/Gunjan/install/miniconda3/envs/instanseg/lib/python3.9/site-packages/pydantic/_migration.py:283: UserWarning: `pydantic.error_wrappers:ValidationError` has been moved to `pydantic:ValidationError`.
>   warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')
>  missing cuda symbols while dynamic loading
>  cuFile initialization failed
> Loading files from:  ../examples
>   0%|                                                                                                                           | 0/2 [00:00<?, ?it/s]Processing file:  ../examples/Fluorescence_example.tif
>   0%|                                                                                                                           | 0/2 [00:03<?, ?it/s]
> Traceback (most recent call last):
>   File "/home/Gunjan/code/instanseg/InstanSeg/scripts/inference.py", line 149, in <module>
>     labels = instanseg(input_tensor[None])
>   File "/home/Gunjan/install/miniconda3/envs/instanseg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/Gunjan/install/miniconda3/envs/instanseg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript, serialized code (most recent call last):
>   File "code/__torch__/InstanSeg/utils/loss/instanseg_loss/___torch_mangle_3796.py", line 49, in forward
>     with _16:
>       fcn = self.fcn
>       x_full = (fcn).forward(x0, )
>                 ~~~~~~~~~~~~ <--- HERE
>       dim_out = (torch.size(x_full))[1]
>       cells_and_nuclei = self.cells_and_nuclei
>   File "code/__torch__/InstanSeg/utils/models/ChannelInvariantNet.py", line 12, in forward
>     model0 = self.model
>     AdaptorNet = model0.AdaptorNet
>     _0 = (model).forward((AdaptorNet).forward(x, ), )
>                           ~~~~~~~~~~~~~~~~~~~ <--- HERE
>     return _0
> class ChannelInvariantNet(Module):
>   File "code/__torch__/InstanSeg/utils/models/ChannelInvariantNet.py", line 53, in forward
>     _12 = int(torch.mul(element3, CONSTANTS.c1))
>     input = torch.reshape(x, [_10, 1, _11, _12])
>     _13 = (conv_0).forward(input, dim, _5, element, _9, )
>            ~~~~~~~~~~~~~~~ <--- HERE
>     _14 = (down_1).forward(_13, dim, _4, element, _8, )
>     _15 = (down_2).forward(_14, dim, _3, element, _7, )
>   File "code/__torch__/InstanSeg/utils/models/ChannelInvariantNet.py", line 86, in forward
>     maxpool = self.maxpool
>     _18 = (maxpool).forward()
>     _19 = (conv0).forward(input, )
>            ~~~~~~~~~~~~~~ <--- HERE
>     _20 = (conv2).forward((conv1).forward(input, ), )
>     input1 = torch.add(_19, _20)
>   File "code/__torch__/torch/nn/modules/container/___torch_mangle_3243.py", line 14, in forward
>     _1 = getattr(self, "1")
>     _0 = getattr(self, "0")
>     _3 = (_1).forward((_0).forward(input, ), )
>                        ~~~~~~~~~~~ <--- HERE
>     return (_2).forward(_3, )
>   File "code/__torch__/torch/nn/modules/conv/___torch_mangle_3240.py", line 12, in forward
>     bias = self.bias
>     weight = self.weight
>     input0 = torch._convolution(input, weight, bias, [1, 1], [0, 0], [1, 1], False, [0, 0], 1, False, False, True, True)
>              ~~~~~~~~~~~~~~~~~~ <--- HERE
>     return input0
>  
> Traceback of TorchScript, original code (most recent call last):
>   File "/home/thibaut_goldsborough/Documents/Projects/Project_InstanSeg/InstanSeg_Public/instanseg_thibaut/InstanSeg/utils/loss/instanseg_loss.py", line 1250, in forward
>        # with torch.autocast(device_type='cuda', dtype=torch.float16):
>         with torch.no_grad():
>             x_full = self.fcn(x)
>                      ~~~~~~~~ <--- HERE
>     
>             dim_out = x_full.shape[1]
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/conv.py(456): _conv_forward
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/conv.py(460): forward
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/module.py(1508): _slow_forward
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/module.py(1527): _call_impl
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/container.py(215): forward
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/module.py(1508): _slow_forward
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/module.py(1527): _call_impl
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
> /home/thibaut_goldsborough/Documents/Projects/Project_InstanSeg/InstanSeg_Public/instanseg_thibaut/InstanSeg/utils/models/InstanSeg_UNet.py(147): forward
> /home/thibaut_goldsborough/Documents/Projects/Project_InstanSeg/InstanSeg_Public/instanseg_thibaut/InstanSeg/utils/models/ChannelInvariantNet.py(40): forward
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/module.py(1508): _slow_forward
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/module.py(1527): _call_impl
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
> /home/thibaut_goldsborough/Documents/Projects/Project_InstanSeg/InstanSeg_Public/instanseg_thibaut/InstanSeg/utils/models/ChannelInvariantNet.py(142): forward
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/module.py(1508): _slow_forward
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/module.py(1527): _call_impl
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
> /home/thibaut_goldsborough/Documents/Projects/Project_InstanSeg/InstanSeg_Public/instanseg_thibaut/InstanSeg/utils/models/ChannelInvariantNet.py(189): forward
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/module.py(1508): _slow_forward
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/module.py(1527): _call_impl
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/jit/_trace.py(1065): trace_module
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/torch/jit/_trace.py(798): trace
> /home/thibaut_goldsborough/Documents/Projects/Project_InstanSeg/InstanSeg_Public/instanseg_thibaut/InstanSeg/utils/loss/instanseg_loss.py(1199): __init__
> /home/thibaut_goldsborough/Documents/Projects/Project_InstanSeg/InstanSeg_Public/instanseg_thibaut/InstanSeg/utils/utils.py(758): export_to_torchscript
> /tmp/ipykernel_81741/1679692337.py(5): <module>
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/IPython/core/interactiveshell.py(3550): run_code
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/IPython/core/interactiveshell.py(3490): run_ast_nodes
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/IPython/core/interactiveshell.py(3308): run_cell_async
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/IPython/core/async_helpers.py(129): _pseudo_sync_runner
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/IPython/core/interactiveshell.py(3103): _run_cell
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/IPython/core/interactiveshell.py(3048): run_cell
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/ipykernel/zmqshell.py(549): run_cell
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/ipykernel/ipkernel.py(429): do_execute
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/ipykernel/kernelbase.py(767): execute_request
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/ipykernel/kernelbase.py(429): dispatch_shell
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/ipykernel/kernelbase.py(523): process_one
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/ipykernel/kernelbase.py(534): dispatch_queue
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/asyncio/events.py(80): _run
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/asyncio/base_events.py(1905): _run_once
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/asyncio/base_events.py(601): run_forever
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/tornado/platform/asyncio.py(205): start
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/ipykernel/kernelapp.py(701): start
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/traitlets/config/application.py(1075): launch_instance
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/site-packages/ipykernel_launcher.py(17): <module>
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/runpy.py(87): _run_code
> /home/thibaut_goldsborough/micromamba/envs/instanseg3/lib/python3.9/runpy.py(197): _run_module_as_main
> RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.FloatTensor) should be the same
> 

P.S.
I setup the environment using miniconda. Installed pytorch CUDA version 11.8 compatible with the nvidia GPU driver I have, as mentioned in the instructions.

Thanks.

**Comment by ThibautGoldsborough** [comment]
Hello, it seems your having issues with pytorch half tensors (we use float32 for training but float16 for inference). I assume it runs fine on the cpu? 

Our instructions suggest CUDA 12.1 (`micromamba install pytorch==2.1.1 torchvision==0.16.1 monai=1.3.0 pytorch-cuda=12.1 -c conda-forge -c pytorch -c nvidia`) but newer versions also work. You may want to update cuda.

n.b. the pixel size parameter should not be 0.5 by default. It should be set to the pixel size of your image. If InstanSeg throws an error, it means that pixel size parameter has been deleted/lost from your image metadata. If you read the specs of your microscope you'll be able to recover that value.
