### ISSUE TITLE
Models not available

### ISSUE THREAD

**Issue by Tomvl117** [instanseg/instanseg#70]
Hi!

Been trying to run Instanseg, and since a couple of minutes I get this issue:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2024.1.4\plugins\python-ce\helpers\pydev\pydevd.py", line 1551, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2024.1.4\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "[...]\cellstitch-instanseg\scripts\main.py", line 260, in <module>
    model = InstanSeg("fluorescence_nuclei_and_cells")
  File "[...]\envs\cellstitch\lib\site-packages\instanseg\instanseg.py", line 118, in __init__
    self.instanseg = download_model(model_type, verbose = self.verbose)
  File "[...]\envs\cellstitch\lib\site-packages\instanseg\utils\utils.py", line 858, in download_model
    response.raise_for_status()  # Raise an error for bad response
  File "[...]\envs\cellstitch\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/instanseg/instanseg/releases/tags/instanseg_models_v1
```

I see there are some efforts to change the model downloading, could it have to do with that?

Cheers!

**Comment by Tomvl117** [comment]
Can confirm!
